### ISSUE TITLE
Consider placing the taskkill stuff inside the service's .xml file

### ISSUE THREAD

**Issue by gurok** [sheggi/win-service-php-cgi#1]
Hi, first off, thanks for this guide. It was a great starting point.

I found I could simplify your setup a little by just including the stopexecutable and stoparguments for taskkill in the .xml file instead of a separate .cmd/.bat file:

```
  <stopexecutable>C:\Windows\system32\taskkill.exe</stopexecutable>
  <stopargument>/f</stopargument>
  <stopargument>/IM</stopargument>
  <stopargument>php-cgi.exe</stopargument>
```

Just something to consider. A great guide nonetheless!

**Comment by sheggi** [comment]
hey @gurok 
thank you for the improvement suggestion 👍🏼 

kudos for this guide goes to https://forum.nginx.org/read.php?2,236376
